name: Update EO Free China IPS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'scan_freenew.py' ]
  schedule:
    - cron: '45 3 */7 * *'

concurrency:
  group: scanner
  cancel-in-progress: false

jobs:
  scan-ips:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check
      uses: actions/checkout@v4
      
    - name: Set Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

        
    - name: Set up
      run: |
        python -m pip install --upgrade pip
        pip install httpx
        
    - name: Search for IPS
      run: |
        python scan_freecn.py
      env:
        CONCURRENCY: 55
        TIMEOUT: 12.0
        RANGE_FILE: range-cn.txt
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: available-ips
        path: available_eofreecn_ips.txt
        retention-days: 30
        
    - name: Update file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add available_eofreecn_ips.txt
        git commit -m "ðŸ“ˆ $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
